export const serviceData: Record<string, {
  title: string;
  metaTitle: string;
  description: string;
  hero: string;
  details: string[];
  faq: { q: string; a: string }[];
  /** Arbeitsfotos fuer die Galerie. Alt-Texte beschreiben Motiv, Stil und Ort
   *  — so findet die Google-Bildersuche sie ueberhaupt erst. */
  bilder?: { src: string; alt: string }[];
  /** Preise, uebernommen aus der Preisliste der Startseite (Pricing.tsx).
   *  Aendern sich Preise, muessen BEIDE Stellen angefasst werden. */
  preise?: { gruppe: string; hinweis?: string; posten: { n: string; p: string }[] }[];
  preisHinweise?: string[];
}> = {
  tattoos: {
    title: "Tattoos",
    metaTitle: "Tattoos in Marchtrenk | Fine-Line, Cover-Up & mehr",
    description: "Professionelle Tattoos in Marchtrenk bei Wels: Fine-Line, Black & Grey, Mandala, Watercolor, Mini-Tattoos, Cover-Ups & Narbenüberdeckung von Eve Paule.",
    hero: "Dein Motiv. Deine Geschichte. Meine Kunst.",
    details: [
      "Fine-Line & filigrane Motive — detailreich und präzise",
      "Black & Grey — klassische Schattierungen mit Tiefe",
      "Mandala & Ornamente — geometrische Kunstwerke",
      "Watercolor — farbenfrohe Designs mit Aquarell-Effekt",
      "Mini-Tattoos — kleine Kunstwerke mit großer Bedeutung",
      "Finger-Tattoos — wenige Studios bieten es an, ich schon!",
      "Cover-Ups — kostenloses Beratungsgespräch vorher",
      "Tattoo-Auffrischung — Farben & Linien nachziehen, egal welches Studio",
      "Narbenüberdeckungen — kleinere Narben kunstvoll kaschieren",
      "Individuelle Zeichnungen — Wunschmotiv persönlich im Studio besprechen",
      "Nachstechen innerhalb 14 Tagen kostenlos bei übermäßigem Farbverlust",
    ],
    bilder: [
      { src: "/images/leistungen/tattoo-minnie-mickey-watercolor.webp", alt: "Minnie- und Mickey-Tattoo im Watercolor-Stil am Oberschenkel, gestochen bei SkinLove in Marchtrenk" },
      { src: "/images/leistungen/tattoo-arielle-meerjungfrau-farbe.webp", alt: "Buntes Arielle-Tattoo am Oberschenkel von SkinLove Marchtrenk" },
      { src: "/images/leistungen/tattoo-stitch-ohana-watercolor.webp", alt: "Stitch-und-Angel-Tattoo mit Ohana-Schriftzug im Watercolor-Stil, SkinLove Marchtrenk" },
      { src: "/images/leistungen/tattoo-drache-ohnezahn-watercolor.webp", alt: "Ohnezahn-Drachen-Tattoo im Watercolor-Stil an der Wade, SkinLove Marchtrenk" },
      { src: "/images/leistungen/tattoo-fuchs-mond-watercolor.webp", alt: "Fuchs-Tattoo mit Mond im Watercolor-Stil am Unterarm, SkinLove Marchtrenk" },
      { src: "/images/leistungen/tattoo-schmetterling-blueten-farbe.webp", alt: "Farbiges Schmetterling-Tattoo mit Blueten am Unterarm, SkinLove Marchtrenk" },
      { src: "/images/leistungen/tattoo-hakuna-matata-watercolor.webp", alt: "Hakuna-Matata-Tattoo im Watercolor-Stil am Oberarm, SkinLove Marchtrenk" },
      { src: "/images/leistungen/tattoo-fuchs-blumen-oberarm.webp", alt: "Grosses Fuchs-Tattoo mit Blumen und Schmetterlingen am Oberarm, SkinLove Marchtrenk" },
      { src: "/images/leistungen/tattoo-stitch-angel-partner.webp", alt: "Stitch-und-Angel-Partnertattoos an beiden Waden im Watercolor-Stil, SkinLove Marchtrenk" },
      { src: "/images/leistungen/tattoo-rose-fine-line-wade.webp", alt: "Fine-Line-Rose mit Mond an der Wade samt Zeichenvorlage, SkinLove Marchtrenk" },
      { src: "/images/leistungen/tattoo-schlange-pfingstrose.webp", alt: "Schlange mit Pfingstrose in Black and Grey am Oberschenkel, SkinLove Marchtrenk" },
      { src: "/images/leistungen/tattoo-rabe-buecher-blackwork.webp", alt: "Rabe auf Buechern in Black and Grey am Oberschenkel samt Vorlage, SkinLove Marchtrenk" },
      { src: "/images/leistungen/tattoo-schildkroete-fine-line.webp", alt: "Fine-Line-Schildkroete am Unterarm, SkinLove Marchtrenk" },
      { src: "/images/leistungen/tattoo-schmetterling-blueten-sw.webp", alt: "Schmetterling mit Blueten in Black and Grey am Unterarm, SkinLove Marchtrenk" },
      { src: "/images/leistungen/tattoo-buecher-tasse-fine-line.webp", alt: "Fine-Line-Tattoo mit Buecherstapel und Teetasse am Oberarm, SkinLove Marchtrenk" },
      { src: "/images/leistungen/tattoo-katze-sketch-stil.webp", alt: "Katzen-Tattoo im Sketch-Stil am Unterarm, SkinLove Marchtrenk" },
      { src: "/images/leistungen/tattoo-babyfuss-abdruck-name.webp", alt: "Tattoo eines Babyfuss-Abdrucks mit Namen am Unterarm, SkinLove Marchtrenk" },
    ],
    faq: [
      { q: "Wie viel kostet ein Tattoo?", a: "Der Preis hängt von Größe, Motiv und Aufwand ab. Meld dich bei mir für ein kostenloses Beratungsgespräch!" },
      { q: "Tut es sehr weh?", a: "Die Schmerzempfindung ist individuell. Die meisten Stellen sind gut auszuhalten — ich geh auf dein Tempo ein." },
      { q: "Wie pflege ich mein neues Tattoo?", a: "Du bekommst nach dem Stechen eine genaue Pflegeanleitung. Prontolind Spray & Gel gibt's direkt im Studio." },
      { q: "Wie lange dauert ein Tattoo-Termin?", a: "Je nach Größe und Komplexität: Mini-Tattoos ca. 30-60 Min, größere Motive können mehrere Stunden dauern. Pausen sind jederzeit möglich." },
      { q: "Kann ich mein eigenes Motiv mitbringen?", a: "Auf jeden Fall! Bring Vorlagen, Fotos oder Skizzen mit — wir besprechen alles persönlich und ich zeichne dein Wunschmotiv." },
      { q: "Was muss ich vor dem Termin beachten?", a: "Kein Alkohol 24h vorher, ausgeschlafen kommen, gut gegessen haben. Keine blutverdünnenden Medikamente. Bequeme Kleidung anziehen." },
      { q: "Ist Nachstechen wirklich kostenlos?", a: "Ja! Innerhalb von 14 Tagen nach dem Stechen ist Nachstechen bei übermäßigem Farbverlust kostenlos." },
    ],
  },
  piercings: {
    title: "Piercings",
    metaTitle: "Piercings in Marchtrenk | Nase, Ohr, Bauchnabel & mehr",
    description: "Professionelle Piercings in Marchtrenk: Nase, Ohr, Septum, Helix, Tragus, Bauchnabel, Zunge, Lippe, Brustwarze & Intimbereich bei SkinLove.",
    hero: "Professionell gestochen. Mit Feingefühl.",
    details: [
      "Nase: Nostril, Septum, Bridge, Nassallang",
      "Ohr: Lobe, Helix, Tragus, Conch, Rook, Industrial, Daith/Migräne",
      "Surface: Augenbraue, Anti Eyebrow, Oberflächen-Piercings",
      "Bauchnabel: Standard, Doppelt, 4-fach",
      "Oral: Zunge, Doppelt/Snake, Lippenbändchen (Smiley)",
      "Lippe: Madonna, Labret, Medusa, Bites, Ashley",
      "Brustwarze: Einzel oder Beide",
      "Intimbereich: Komplettes Angebot für Damen & Herren",
      "Alles inkl. Schmuck & Kontrolltermin",
    ],
    preise: [
      { gruppe: "Nase", posten: [
        { n: "Nasenflügel (Nostril) einfach", p: "53 €" },
        { n: "Bridge", p: "84 €" },
        { n: "Septum", p: "65 €" },
        { n: "Nassallang (mittig durchgehend) / Austin Bar", p: "132 €" },
      ] },
      { gruppe: "Ohr", posten: [
        { n: "Lobe / Horizontal Lobe / Standard Lobe / Upper Lobe", p: "42 €" },
        { n: "Forward Helix / Helix Rim / Helix / AntiHelix-Sung", p: "55 €" },
        { n: "Tragus / Anti Tragus", p: "60 €" },
        { n: "Rook / Conch / Flat / Orbital / Snug / Inner Conch", p: "65 €" },
        { n: "Industrial / Vertikal Industrial", p: "75 €" },
        { n: "Daith (Migräne Piercing) / Surface Tragus / Trimix", p: "70 €" },
      ] },
      { gruppe: "Surface", posten: [
        { n: "Augenbraue", p: "60 €" },
        { n: "Anti Eyebrow", p: "62 €" },
        { n: "Oberflächenpiercings (Nacken, Bauch, Brustbein, Finger, Arme)", p: "72 €" },
      ] },
      { gruppe: "Bauchnabel", posten: [
        { n: "Standard / Unten / Seitlich", p: "65 €" },
        { n: "Doppelt (oben & unten)", p: "122 €" },
        { n: "Stern 4-fach", p: "247 €" },
        { n: "Dreieck", p: "187 €" },
      ] },
      { gruppe: "Oral", posten: [
        { n: "Zungen-Piercing (Standard)", p: "72 €" },
        { n: "Doppelt / Vertical / Snake / Zungenspitze", p: "88 €" },
        { n: "Zungenbändchen / Scoop / Venom", p: "88 €" },
      ] },
      { gruppe: "Lippe", posten: [
        { n: "Lippenbändchen", p: "60 €" },
        { n: "Lippenbereich (Madonna, Labret, Medusa)", p: "64 €" },
        { n: "Angel Bites / Cyber Bites / Daliha Bites / Dimple / Vampire", p: "115 €" },
        { n: "Snake Bites / Horizontal Lips / Shark Bites", p: "117 €" },
        { n: "Triangle Bites & Cheek", p: "112 €" },
        { n: "Eskimo / Horizontal Labret / Jestrum", p: "77 €" },
        { n: "Horizontales Oberlippenpiercing / Ashley", p: "77 €" },
      ] },
      { gruppe: "Brustwarze", hinweis: "Ab 16 Jahre", posten: [
        { n: "Horizontal / Vertikal", p: "72 €" },
        { n: "Beide gemeinsam (rechts & links)", p: "132 €" },
      ] },
      { gruppe: "Intim Damen", hinweis: "Ab 16 Jahre", posten: [
        { n: "Christina", p: "112 €" },
        { n: "Klitoris Vorhaut / Isabella / Hymen", p: "112 €" },
        { n: "Äußere Schamlippe", p: "112 €" },
        { n: "Innere Schamlippe", p: "112 €" },
        { n: "Anus / Guiche / Fourchette", p: "142 €" },
        { n: "Pubic Piercing", p: "242 €" },
        { n: "Keuschheitspiercing", p: "252 €" },
        { n: "Magic Cross / Prinzessin Diana", p: "210 €" },
        { n: "Triangle Piercing", p: "242 €" },
        { n: "Nefertiti Piercing", p: "137 €" },
      ] },
      { gruppe: "Intim Herren", hinweis: "Ab 16 Jahre", posten: [
        { n: "Ampallang", p: "260 €" },
        { n: "Deep Dydoe", p: "260 €" },
        { n: "Dydoe", p: "180 €" },
        { n: "Frenulum", p: "110 €" },
        { n: "Guiche", p: "160 €" },
        { n: "Hafada", p: "140 €" },
        { n: "Lorum", p: "120 €" },
        { n: "Oetang / Vorhaut", p: "130 €" },
        { n: "Pubic", p: "190 €" },
        { n: "Schaft-Ampallang", p: "260 €" },
        { n: "Scrotal Ladder (3-4 Stück)", p: "290 €" },
      ] },
    ],
    preisHinweise: [
      "Alle Piercings inkl. Schmuck & Kontrolltermin · Gültig ab 1.1.2026",
      "Piercen ab 14 Jahre in Anwesenheit eines Erziehungsberechtigten, ab 16 Jahre alleine.",
      "Falls du ein Piercing möchtest, das hier nicht aufgezählt ist, ruf mich gerne an!",
    ],
    faq: [
      { q: "Ab welchem Alter kann ich mir ein Piercing stechen lassen?", a: "Unter 16 mit schriftlicher Einverständniserklärung der Eltern. Ab 16 mit Begleitperson, ab 18 eigenständig." },
      { q: "Wie lange dauert die Heilung?", a: "Je nach Stelle 4 Wochen (Ohrläppchen) bis 12 Monate (Bauchnabel). Du bekommst eine genaue Pflegeanleitung." },
      { q: "Ist der Schmuck im Preis inbegriffen?", a: "Ja! Bei jedem Piercing ist der passende Erstschmuck inklusive, plus ein kostenloser Kontrolltermin." },
      { q: "Welches Material wird verwendet?", a: "Wir arbeiten mit Titan und chirurgischem Stahl — hypoallergen und bestens verträglich." },
      { q: "Kann ich Sport machen nach dem Piercing?", a: "Leichte Bewegung ist okay, aber Schwimmbad, Sauna und starkes Schwitzen solltest du in den ersten Wochen vermeiden." },
      { q: "Was mache ich bei Problemen nach dem Stechen?", a: "Komm einfach vorbei! Kontrolltermine sind kostenlos. Bei Wildfleisch oder Entzündungen helfen wir sofort." },
    ],
  },
  "permanent-make-up": {
    title: "Permanent Make-up",
    metaTitle: "Permanent Make-up Marchtrenk | Augenbrauen & Lippen",
    description: "Permanent Make-up in Marchtrenk: Natürlich gezeichnete Augenbrauen & Lippen. Langanhaltend, individuell, von Eve Paule bei SkinLove.",
    hero: "Natürliche Schönheit. Dauerhaft betont.",
    details: [
      "Augenbrauen — natürlich gezeichnet, typgerecht angepasst",
      "Lippen — dezente Schattierung für mehr Ausdruck",
      "Langanhaltend — erleichtert den Alltag, kein tägliches Nachziehen",
      "Präzise Arbeit mit modernstem Equipment",
      "Individuelle Beratung vor jeder Behandlung",
      "Auffrischung nach 4-6 Wochen empfohlen",
    ],
    faq: [
      { q: "Wie lange hält Permanent Make-up?", a: "In der Regel 1-3 Jahre, je nach Hauttyp und Pflege. Auffrischungen sind möglich." },
      { q: "Ist es schmerzhaft?", a: "Eine Betäubungscreme wird aufgetragen. Die meisten empfinden nur ein leichtes Kratzen." },
      { q: "Wie sieht es direkt nach der Behandlung aus?", a: "In den ersten Tagen ist die Farbe intensiver. Nach 1-2 Wochen heilt es ab und die endgültige Farbe zeigt sich." },
      { q: "Kann ich Permanent Make-up entfernen lassen?", a: "Es verblasst natürlich über die Jahre. Für eine vorzeitige Entfernung gibt es spezielle Verfahren — sprich mich an." },
      { q: "Wer ist für Permanent Make-up geeignet?", a: "Fast jeder! Bei Schwangerschaft, Stillzeit, Blutverdünnern oder bestimmten Hauterkrankungen bitte vorher abklären." },
    ],
  },
  "lash-brow-lifting": {
    title: "Lash & Brow Lifting",
    metaTitle: "Lash & Brow Lifting Marchtrenk | inkl. Färben & Keratin",
    description: "Lash Lifting & Brow Lifting in Marchtrenk: Naturwimpern sanft geformt, inkl. Färben & Keratin. Ausdrucksstarke Augenbrauen bei SkinLove.",
    hero: "Dein Blick. Dein Statement.",
    details: [
      "Lash Lifting inkl. Färben & Keratin-Pflege",
      "Brow Lifting inkl. Färben & Keratin-Pflege",
      "Kombi Lash & Brow inkl. Zupfen — das volle Programm",
      "Hält 6-9 Wochen",
      "Sanfte Behandlung, kein Kleber, keine Extensions",
      "Natürlicher WOW-Effekt vom ersten Tag an",
    ],
    preise: [
      { gruppe: "Lash & Brow Lifting", posten: [
        { n: "Lash Lifting inkl. Färben & Keratin", p: "61 €" },
        { n: "Brow Lifting inkl. Färben & Keratin", p: "52 €" },
        { n: "Lash & Brow Lifting inkl. Färben, Keratin & Zupfen", p: "110 €" },
        { n: "Augenbrauen zupfen (nur in Kombination)", p: "15 €" },
      ] },
    ],
    preisHinweise: [
      "Preise gültig ab 1.1.2026 · Anzahlung für Kombi Lash & Brow: 40 €",
      "Empfohlen alle 6–9 Wochen.",
    ],
    faq: [
      { q: "Wie oft sollte ich das wiederholen?", a: "Alle 6-9 Wochen für dauerhaft schöne Wimpern & Brauen." },
      { q: "Kann ich danach Mascara benutzen?", a: "Ja, nach 24 Stunden. Aber die meisten brauchen keine mehr! 😉" },
      { q: "Ist Lash Lifting schädlich für die Wimpern?", a: "Nein! Durch die Keratin-Pflege werden die Wimpern sogar gestärkt. Kein Kleber, keine Extensions." },
      { q: "Wie lange dauert die Behandlung?", a: "Lash Lifting ca. 45-60 Min, Brow Lifting ca. 30 Min. Kombi ca. 75-90 Min." },
      { q: "Darf ich danach Kontaktlinsen tragen?", a: "Ja, nach ca. 2 Stunden. Am besten mit Brille zum Termin kommen." },
    ],
  },
  kinderohrringe: {
    title: "Kinderohrringe",
    metaTitle: "Kinderohrringe stechen Marchtrenk | Studex System, ab 6 Monate",
    description: "Kinderohrringe stechen in Marchtrenk: Sanft, schmerzarm & sicher mit dem Studex-System. Ab 6 Monaten bei SkinLove.",
    hero: "Sanft & sicher. Für die Kleinsten.",
    details: [
      "Studex-System — kein Schießen, speziell für empfindliche Kinderhaut",
      "Ab 6 Monaten möglich",
      "Ab 8 Jahren auch andere Ohrringe mit Nadel möglich",
      "Verschiedene süße Motiv-Designs verfügbar",
      "Entspannte Atmosphäre für Kinder und Eltern",
      "Inkl. Pflegehinweise für die Eltern",
    ],
    faq: [
      { q: "Ist es sicher für kleine Kinder?", a: "Ja! Das Studex-System ist speziell für Kinder entwickelt — kein Schuss, minimal schmerzarm, medizinisch getestet." },
      { q: "Welchen Schmuck verwenden Sie?", a: "Hypoallergene Studex-Ohrstecker aus chirurgischem Stahl oder Titan." },
      { q: "Wie pflege ich die Ohrringe meines Kindes?", a: "2x täglich mit Prontolind reinigen, Ohrstecker leicht drehen. Nicht rausnehmen für mindestens 6 Wochen." },
      { q: "Werden beide Ohren gleichzeitig gestochen?", a: "Ja, bei uns werden immer beide Ohren gleichzeitig gestochen — schnell und stressfrei für dein Kind." },
      { q: "Muss ich einen Termin vereinbaren?", a: "Ja, damit wir genug Zeit und Ruhe für dein Kind haben. Einfach kurz melden!" },
    ],
  },
  spezialleistungen: {
    title: "Spezialleistungen",
    metaTitle: "Spezialleistungen Marchtrenk | Wildfleisch, Dermal Anker & mehr",
    description: "Spezialleistungen bei SkinLove in Marchtrenk: Wildfleischbehandlung, Dermal Anker Entfernung, Piercing-Korrekturen, Nachstechen & kostenlose Erstberatung.",
    hero: "Mehr als Tattoo & Piercing.",
    details: [
      "Wildfleischbehandlung — professionelle Behandlung von Granulationsgewebe",
      "Dermal Anker Entfernung — fachgerecht mit minimalem Narbenrisiko",
      "Nachstechen gratis innerhalb von 14 Tagen bei übermäßigem Farbverlust",
      "Kostenlose Beratung & Erstgespräche jederzeit",
      "Piercing-Korrekturen bei Fehlstichen aus anderen Studios",
      "Prontolind Spray & Gel für optimale Pflege — direkt im Studio erhältlich",
      "Stecker kürzen, Fremdschmuck wechseln, Dehnen",
    ],
    preise: [
      { gruppe: "Pflege & Service", posten: [
        { n: "Wildfleischbehandlung inkl. Spezialmaterial", p: "40 €" },
        { n: "Dermal Anker Entfernung (exkl. Schmuck & Pflege)", p: "60 €" },
        { n: "Dehnen bis 4 mm", p: "35 €" },
        { n: "Fremdschmuck wechseln", p: "15 €" },
        { n: "Stecker kürzen", p: "6 €" },
        { n: "Prontolind Spray", p: "10 €" },
        { n: "Prontolind Gel", p: "7 €" },
      ] },
    ],
    preisHinweise: [ "Gültig ab 1.1.2026" ],
    faq: [
      { q: "Was ist Wildfleisch und wie wird es behandelt?", a: "Wildfleisch (Granulationsgewebe) entsteht manchmal bei Piercings. Wir behandeln es professionell — meld dich einfach bei uns." },
      { q: "Kann ich auch Schmuck von anderen Studios wechseln lassen?", a: "Ja klar! Komm einfach vorbei — Fremdschmuck wechseln ist kein Problem." },
      { q: "Kostet die Erstberatung etwas?", a: "Nein, Beratung und Erstgespräch sind bei uns immer kostenlos!" },
      { q: "Kann ich Piercings aus anderen Studios korrigieren lassen?", a: "Ja! Wir korrigieren Fehlstiche und beraten dich ehrlich, was möglich ist." },
      { q: "Wo bekomme ich Pflegeprodukte?", a: "Prontolind Spray & Gel gibt's direkt bei uns im Studio — die beste Pflege für Piercings und Tattoos." },
    ],
  },
};

export const slugs = Object.keys(serviceData);
